app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id)) 
class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(300))
    email = db.Column(db.String(300),unique=True, index= True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(400))
    profile_pic = db.Column(db.String())
    pass_s = db.Column(db.String(300))

    def __repr__(self):
        return f'User {self.username}'

    @property
    def password(self):
        raise AttributeError('this is restriced')

    @password.setter
    def password(self,password):
        self.pass_s = generate_password_hash(password)

    def verify_hash(self,password):
        return check_password_hash(self.pass_s,password)

    

class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(300))
    user = db.relationship('User',backref='role', lazy="dynamic")

    def __repr__(self):
        return f'Role {self.title}'
class Movie:
    '''
    Movie class to define Movie Objects
    '''

    def __init__(self,id,title,overview,poster,vote_average,vote_count):
        self.id =id
        self.title = title
        self.overview = overview
        self.poster = "https://image.tmdb.org/t/p/w500/" + poster
        self.vote_average = vote_average
        self.vote_count = vote_count



class Review:

    all_reviews = []

    def __init__(self,movie_id,title,imageurl,review):
        self.movie_id = movie_id
        self.title = title
        self.imageurl = imageurl
        self.review = review


    def save_review(self):
        Review.all_reviews.append(self)


    @classmethod
    def clear_reviews(cls):
        Review.all_reviews.clear()

    @classmethod
    def get_reviews(cls,id):

        response = []

        for review in cls.all_reviews:
            if review.movie_id == id:
                response.append(review)

        return response

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import InputRequired

class ReviewForm(FlaskForm):

    title = StringField('Review title',validators=[InputRequired()])
    review = TextAreaField('Movie review', validators=[InputRequired()])
    submit = SubmitField('Submit')

class ProfileForm(FlaskForm):
    bio = TextAreaField('Tell us about yourself', validators=[InputRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import IMAGES,UploadSet, configure_uploads
from flask_mail import Mail

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)
mail = Mail()
def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])


    configure_uploads(app,photos)
    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/authention')
    # setting config
    from .requests import configure_request
    configure_request(app)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import redirect, render_template, request, url_for, abort
from flask_login import login_required

from ..models import Review, User
from ..requests import get_movie, get_movies, search_movie
from . import main
from .forms import ReviewForm, ProfileForm
from .. import db,photos

# Views
@main.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''

    # Getting popular movie
    popular_movies = get_movies('popular')
    upcoming_movie = get_movies('upcoming')
    now_showing_movie = get_movies('now_playing')

    title = 'Home - Welcome to The best Movie Review Website Online'

    search_movie = request.args.get('movie_query')

    if search_movie:
        return redirect(url_for('.search',movie_name=search_movie))
    else:
        return render_template('index.html', title = title, popular = popular_movies, upcoming = upcoming_movie, now_showing = now_showing_movie )


@main.route('/movie/review/new/<int:id>', methods = ['GET','POST'])
@login_required
def new_review(id):
    form = ReviewForm()
    movie = get_movie(id)

    if form.validate_on_submit():
        title = form.title.data
        review = form.review.data
        new_review = Review(movie.id,title,movie.poster,review)
        new_review.save_review()
        return redirect(url_for('.movie',id = movie.id ))

    title = f'{movie.title} review'
    return render_template('new_review.html',title = title, review_form=form, movie=movie)

@main.route('/movie/<int:id>')
def movie(id):

    '''
    View movie page function that returns the movie details page and its data
    '''
    movie = get_movie(id)
    title = f'{movie.title}'
    reviews = Review.get_reviews(movie.id)

    return render_template('movie.html',title = title,movie = movie,reviews = reviews)

@main.route('/search/<movie_name>')
def search(movie_name):
    '''
    View function to display the search results
    '''
    movie_name_list = movie_name.split(" ")
    movie_name_format = "+".join(movie_name_list)
    searched_movies = search_movie(movie_name_format)
    title = f'search results for {movie_name}'
    return render_template('search.html',movies = searched_movies)

@main.route('/profile/<user_name>')
def profile(user_name):
    user = User.query.filter_by(username=user_name).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user=user)

@main.route('/profile/<user_name>/update', methods=["GET","POST"])
def update_profile(user_name):
    user= User.query.filter_by(username=user_name).first()
    if user is None:
        abort(404)
    profile_form = ProfileForm()
    if profile_form.validate_on_submit():
        user.bio = profile_form.bio.data
        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', user_name=user.username))
    return render_template('profile/update.html', profile_form=profile_form)

@main.route('/profile/<user_name>/update/pic', methods=["POST"])
def profile_pic(user_name):
    user= User.query.filter_by(username=user_name).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic = path
        db.session.commit()
    return redirect(url_for('main.profile', user_name=user_name))

app/templates/authentic/login.html
{% extends './base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="contaner">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
             
            {% for message in get_flashed_message %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">Close</button>
                {{message}}
            </div>
            {% endfor %}

            {{wtf.quick_form(login_form)}}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

app/templates/authentic/registration.html
{% extends './base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="contaner">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            {{wtf.quick_form(form)}}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  --> 

{% include 'navbar.html' %}

{% block content %}
{% endblock %}

app/templates/fourOwFour.html
{% extends 'base.html'%}

{% block content %}
    <h1>Whoopsie :) we can't find that page</h1>
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>Whoopsie :) we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

<!-- Styles block -->

{% block styles%}
{{ super() }}
<link href="https://fonts.googleapis.com/css?family=Architects+Daughter" rel="stylesheet">
<link href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/cyborg/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4DAPMwiyOJv/C/LvTiUsW5ueiD7EsaAhwUKO0Llp+fWzT40XrmAbayhVP00bAJVa" crossorigin="anonymous">
{% endblock %}

{% block content %}

<div class="container">
    <form style="display:flex;">
        <input type="text" name="movie_query" placeholder="Search for a Movie" class="form-control">
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
</div>

<div class="container">
    <!-- Popular movie -->
    <h3 align="center"> Popular Movies</h3>
    <ul>
        {{ macro.displayMovieList(popular)}}
    </ul>
    <!-- Upcoming movie  -->
    <h3 align="center"> Upcoming Movies </h3>
    <ul>
        {{ macro.displayMovieList(upcoming)}}
    </ul>
    <!-- Now showing movie -->
    <h3 align="center">Now Showing</h3>
    <ul>
        {{ macro.displayMovieList(now_showing)}}
    </ul>
</div>
{% endblock %}

app/templates/macros.html
{% macro displayMovieList(movie_list) %}

{% for movie in movie_list %}

<div class="card mb-3 col-md-3">
    <a class="list-group-item list-group-item-action active" href="/movie/{{movie.id}}">
        <li style="list-style: none">{{movie.title}}</li>

        <img style="height: auto; width: 100%; display: block;" src="{{movie.poster}}" alt="{{movie.title}}"
            padding="120px">
    </a>
</div>

{% endfor %}
{% endmacro %}

<!-- Displaying reviews macro -->
{% macro displayReviews(review_list) %}
{% for review in review_list %}
<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 review-card">
    <h2> {{ review.title}} </h2>
    <p> {{ review.review | truncate(30) }}</p>
</div>
{% endfor %}
{% endmacro %}

app/templates/movie.html
{% extends 'base.html' %}
{% import 'macros.html' as macro%}

{% block content %}

<div class="container">
    <div class="row">

        <h1>Reviews</h1>
        <hr>

        {% if reviews %}
        {{macro.displayReviews(reviews)}}

        {% else%}
        <h3 class="text-center">This movie has no reviews </h3>

        <a class="btn btn-success btn-lg text-center" href="/movie/review/new/{{movie.id}}"> Write a new review</a>
        {% endif %}

    </div>
</div>
{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Watchlist </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>

            <ul class="nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile', user_name=current_user.username)}}">Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Signout</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Login</a></li>
                <li><a href="{{url_for('auth.register')}}">Signup</a></li>
                {% endif %}
            </ul>
        </div>
        
    
    </div>
</nav>

app/templates/new_review.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">

        <div class="col-md-8">
            <img src="{{movie.poster}}" alt="{{movie.title}}" class="img-responsive">
        </div>

        <div class="col-md-4">

            {{ wtf.quick_form(review_form) }}
        </div>

    </div>

{% endblock %}

app/templates/profile/profile.html
{% extends './base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h5>{{user.username}}</h5>
            {% if user.bio %}
            <p>{{user.bio}}</p>
            {% endif %}

            {% if user== current_user %}
            <a class="btn btn-info" href="{{url_for('main.update_profile',user_name=user.username)}}">Edit Profile</a>
            {% endif %}
        </div>
        <div class="col-md-6">
            {% if user.profile_pic  %}
            <img src="{{url_for('static',filename=user.profile_pic)}}" width="50%" alt="profile-pic">
            {% else %}
            <p>No Profile picture</p>
            <form action="{{url_for('main.profile_pic', user_name= user.username)}}" method="post" enctype="multipart/form-data">
                <input type="file" name="photo" class="form-control" required>
                <input type="submit" >
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends './base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            {{wtf.quick_form(profile_form)}}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

app/templates/search.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

{% block content %}
    <div class="container">

        <div class="row">

            <h5> Found {{ movies| count }} matches </h5>
            <hr>
            <ul>
                {{ macro.displayMovieList(movies)}}
            </ul>

        </div>

    </div>
{% endblock %}